services:
  rabbit:
    build:
      context: .
      dockerfile: configs/rabbitmq/Dockerfile
      args:
        RABBITMQ_ADMIN_USER: "admin"
        RABBITMQ_ADMIN_PASSWORD: "password"
        RABBITMQ_GUEST_USER: "guest"
        RABBITMQ_GUEST_PASSWORD: "guest"
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q status && rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 5

  scrapper:
    build:
      context: .
      dockerfile: scrapper/Dockerfile
    # ports:
    #   - "8000:80"
    depends_on:
      rabbit:
        condition: service_healthy
    environment:
      RABBITMQ_ADMIN_USER: "admin"
      RABBITMQ_ADMIN_PASSWORD: "password"
      RABBITMQ_VHOST: "/"
      RABBITMQ_HOST: "rabbit"
      RABBITMQ_PORT: 5672
      REDIS_SSL: "false"
      LOG_LEVEL: "DEBUG"
      RUST_LOG: "trace"
